name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node v20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"

      - name: Clean Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
